{% set version = "3.2.1" %}
{% set sha256 = "5417789ee6064ff515fd10be24870660af3561c02d3d48b26f6f44285d0f70cc" %}

package:
  name: widgetsnbextension
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/widgetsnbextension/widgetsnbextension-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - notebook >=4.4.1
  run:
    - python
    - notebook >=4.4.1

test:
  imports:
    - widgetsnbextension

about:
  home: http://ipython.org
  license: BSD 3-clause
  summary: Interactive Widgets for Jupyter

extra:
  recipe-maintainers:
    - jasongrout
    - jakirkham
    - minrk
    - pelson
    - SylvainCorlay
    - willingc
    - pbugnion
