{% set version = "3.6.5" %}

package:
  name: widgetsnbextension
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/widgetsnbextension/widgetsnbextension-{{ version }}.tar.gz
  sha256: 601352aa4df7b15717fc57ab59fd9f2795003e53c477dca0d53171c4ee933b35

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - notebook >=4.4.1

test:
  requires:
    - pip
  imports:
    - widgetsnbextension
  commands:
    - pip check

about:
  home: http://jupyter.org
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Jupyter interactive widgets for Jupyter Notebook
  description: Interactive Jupyter widgets for the classic Jupyter Notebook application.
  doc_url: https://ipywidgets.readthedocs.io
  dev_url: https://github.com/jupyter-widgets/ipywidgets/tree/master/python/widgetsnbextension

extra:
  recipe-maintainers:
    - jasongrout
    - jakirkham
    - minrk
    - pelson
    - SylvainCorlay
    - willingc
    - pbugnion
    - ocefpaf
    - bollwyvl
    - martinRenou
