{% set version = "4.0.9" %}

package:
  name: widgetsnbextension
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/widgetsnbextension/widgetsnbextension-{{ version }}.tar.gz
  sha256: 3c1f5e46dc1166dfd40a42d685e6a51396fd34ff878742a3e47c6f0cc4a2a385

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - jupyter-packaging
  run:
    - python >=3.7

test:
  requires:
    - pip
  imports:
    - widgetsnbextension
  commands:
    - pip check

about:
  home: http://jupyter.org
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Jupyter interactive widgets for Jupyter Notebook
  description: Interactive Jupyter widgets for the classic Jupyter Notebook application.
  doc_url: https://ipywidgets.readthedocs.io
  dev_url: https://github.com/jupyter-widgets/ipywidgets/tree/master/python/widgetsnbextension

extra:
  recipe-maintainers:
    - martinRenou
    - jasongrout
    - jakirkham
    - minrk
    - pelson
    - SylvainCorlay
    - willingc
    - pbugnion
    - ocefpaf
    - bollwyvl
