{% set version = "3.3.0" %}
{% set sha256 = "c5280a62d293735cdadc7b8884e2affcfb0488420ee09963577f042359726392" %}

package:
  name: widgetsnbextension
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/widgetsnbextension/widgetsnbextension-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - notebook >=4.4.1
  run:
    - python
    - notebook >=4.4.1

test:
  imports:
    - widgetsnbextension

about:
  home: http://ipython.org
  license: BSD 3-clause
  summary: Interactive Widgets for Jupyter

extra:
  recipe-maintainers:
    - jasongrout
    - jakirkham
    - minrk
    - pelson
    - SylvainCorlay
    - willingc
    - pbugnion
